on:
  push:

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions: write-all

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Define Image Tag
        id: image-tag
        shell: bash
        env:
          USER_AND_REPO: ${{ github.repository }}
        run: echo "tag=${USER_AND_REPO,,}:latest" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        shell: bash
        run: docker build -t ${{ steps.image-tag.outputs.tag }} .
      
      - name: Publish Image to GitHub's Registry
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker push ${{ steps.image-tag.outputs.tag }}
