on:
  push:
    branches:
      - main
    paths:
      - src/*
      - Dockerfile
      - .github/workflows/build-image.yml

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-image:
    runs-on: ubuntu-latest

    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
    
      - name: Define Image Tag
        id: image-tag
        shell: bash
        env:
          USER_AND_REPO: ${{ github.repository }}
        run: echo "tag=ghcr.io/${USER_AND_REPO,,}:latest" >> "$GITHUB_OUTPUT"

      - name: Build Docker Image
        shell: bash
        run: docker build -t ${{ steps.image-tag.outputs.tag }} .

      - name: Publish Image to GitHub's Registry
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: docker push ${{ steps.image-tag.outputs.tag }}
